const TRANSLATIONS = {
  it: {
    /* ── NAV (tutti i page) ── */
    nav_home:        'Home',
    nav_staff:       'Staff',
    nav_teams:       'Teams 2026–2027',
    nav_risultati:   'Risultati Gare',
    nav_stage:       'Stage &amp; Camp',
    nav_news:        'News',
    nav_lmsa:        'MY LMSA',

    /* ── INDEX · HERO ── */
    hero_eyebrow:    'Milano · Synchro Academy · Dal 1998',
    hero_h1:         'Pattinaggio<br>Sincronizzato<br>a <em>Milano</em>',
    hero_claim:      'La società di sincronizzato più grande d\'Italia',
    hero_p:          'Dalle prime lame sul ghiaccio ai palcoscenici internazionali, diverse categorie per ogni età e livello.',
    hero_btn_iscr:   'Iscriviti 2026/2027',

    /* ── INDEX · CHI SIAMO ── */
    chi_kicker:      'Chi siamo',
    chi_h2:          'Nate nel 1998,<br>cresciute sul ghiaccio di Milano',
    chi_p1:          'Il pattinaggio sincronizzato è una disciplina spettacolare che richiede grande coordinazione e sintonia tra le atlete. È uno sport di squadra che combina la grazia del pattinaggio artistico con movimenti coreografati eseguiti all\'unisono. La partecipazione a questo sport aiuta a sviluppare la cooperazione, la comunicazione e la fiducia reciproca tra le componenti del team.',
    chi_p2:          'Nata nel 1998, <strong>Ladybirds Milano Synchro Academy</strong> rappresenta un\'eccellenza nel campo del pattinaggio sincronizzato in Italia, contribuendo alla crescita e alla diffusione di questa disciplina sportiva nel paese.',

    /* ── INDEX · FORMAZIONE ── */
    form_kicker:     'Formazione e livelli',
    form_h3:         'Uno sport per<br>ogni livello e ogni età',
    form_p1:         'Attraverso programmi strutturati e personalizzati, accompagniamo ogni atleta in un percorso di crescita completo, dove tecnica, arte ed espressività si uniscono sul ghiaccio.',
    form_p2:         'Aperto ad atleti di ogni livello: da chi muove i primi passi sul ghiaccio agli atleti agonisti, anche provenienti da danza, pattinaggio artistico o altre discipline.',
    form_p3:         'Ogni squadra è formata tenendo conto dell\'età, dell\'esperienza e delle capacità tecniche, per offrire a ogni atleta un percorso progressivo e stimolante.',

    /* ── INDEX · COMPETIZIONI ── */
    comp_kicker:     'Competizioni ed eventi',
    comp_h3:         'Sul ghiaccio<br>e sui palcoscenici del mondo',
    comp_p1:         'Oltre all\'attività agonistica, la nostra società promuove il pattinaggio sincronizzato attraverso eventi, manifestazioni e competizioni nazionali e internazionali.',
    comp_p2:         'Tra questi, organizziamo il <strong style="color:var(--navy);">Milano Easter Trophy</strong>, appuntamento internazionale che porta a Milano squadre e atleti da tutto il mondo, offrendo un\'importante occasione di sport, confronto e crescita.',
    comp_met_link:   'Visita milanoeastertrophy.it →',

    /* ── INDEX · OBIETTIVI ── */
    obiet_kicker:    'Obiettivi educativi e sociali',
    obiet_h3:        'Crescere insieme,<br>dentro e fuori dal ghiaccio',
    obiet_p1:        'In Ladybirds Milano Synchro Academy, lo sport è un percorso di crescita personale. Attraverso il pattinaggio sincronizzato trasmettiamo valori come il lavoro di squadra, la disciplina, la resilienza e la determinazione.',
    obiet_p2:        'La nostra Accademia offre un ambiente positivo, inclusivo e stimolante, dove ogni atleta cresce anche come persona.',

    /* ── INDEX · STAGES BLOCK ── */
    stages_kicker:   'Stages',
    stages_h3:       'Stage &amp; Camp',
    stages_p:        'L\'Accademia organizza camp tematici aperti anche ad atleti provenienti da altre discipline: occasioni speciali per approfondire la tecnica, trovare nuovi stimoli e crescere insieme in un ambiente dinamico, formativo e appassionante.',
    stages_link:     'Informazioni prossimo evento →',

    /* ── INDEX · 5x1000 ── */
    cinquemila_kicker:  'Costa zero',
    cinquemila_h3:      'Dona il tuo<br><em style="color:var(--gold);font-style:italic;">5×1000</em>',
    cinquemila_p:       'Nella dichiarazione dei redditi, nella sezione <strong style="color:#fff;">«Sostegno del volontariato e delle altre organizzazioni non lucrative»</strong>, indica il nostro codice fiscale. Un gesto semplice che aiuta concretamente i nostri atleti.',

    /* ── INDEX · SOSTIENI ── */
    sostieni_kicker:    'Sostieni le Ladybirds',
    sostieni_h3:        'Il tuo supporto fa la differenza',
    sostieni_p1:        'Portare una squadra a gareggiare all\'estero ha un costo reale: trasferte, costumi da gara, stages con coach internazionali, iscrizioni ai campionati. Costi che senza sostegno ricadono interamente sulle famiglie degli atleti.',
    sostieni_p2:        'Sostenere le Ladybirds significa alleggerire questo peso e permettere a atleti di talento di continuare a sognare e competere ad alto livello, indipendentemente dalla capacità economica della propria famiglia.',
    sostieni_btn_partner: 'Diventa partner →',
    sostieni_btn_sponsor: 'Diventa sponsor →',

    /* ── INDEX · STAFF ── */
    staff_kicker:       'Staff Tecnico',
    staff_h2:           'Il nostro team<br>di allenatori',
    staff_p:            'Uno staff internazionale di altissimo livello: tecnici, coach, preparatori e specialisti che lavorano insieme per far crescere ogni atleta, dentro e fuori dal ghiaccio.',
    staff_dir_title:    'Direzione Tecnica',
    staff_dir_role:     'Direttore Tecnico &amp; Head Coach',
    staff_dir_desc:     'Guida tecnica e visione d\'insieme di tutto il settore Ladybirds. Responsabile dello sviluppo delle squadre e della crescita di ogni atleta.',
    staff_cons_title:   'Consulenti Internazionali',
    staff_pascal_role:  'Consulente internazionale · Pattinaggio sincronizzato',
    staff_roberto_role: 'Consulente esterno · Tecnica di pattinata',
    staff_tech_title:   'Staff Tecnico',
    staff_support_title: 'Staff di Supporto',

    /* ── INDEX · TEAMS ── */
    teams_kicker:     'Squadre',
    teams_h2:         'Teams 2026·2027',
    tc_s9_cat:        'Nuova disciplina olimpica',
    tc_s9_desc:       '<p class="tc-desc">9 atleti. Un format completamente nuovo: sfide dirette (head-to-head), turni di eliminazione, performance a tema. Più veloce, più dinamico, pensato per il pubblico di oggi.</p><p class="tc-desc" style="margin-top:.5rem;">Il team Junior debutterà alle Olimpiadi Giovanili 2028 in Italia (Dolomiti Valtellina). Il team Senior alle Olimpiadi Invernali Alpi 2030. Le Ladybirds stanno costruendo entrambe le squadre adesso.</p><p class="tc-desc" style="margin-top:.5rem;">Se hai una solida esperienza nel sincronizzato o nel pattinaggio artistico, questa è la tua occasione per entrare in una storia che sta appena iniziando. <strong>Tryout obbligatorio. Posti limitati.</strong></p>',
    tc_s9_btn:        'Informazioni →',
    tc_isu_cat:       'ISU · Competizioni internazionali',
    tc_isu_desc:      'Gli atleti devono superare un test di selezione interno (twizzles, sequenze di passi, salti, angeli, lune sul filo, trottole). Programma corto e libero; 2-4 competizioni internazionali all\'anno. Stage estivo e stage tematici obbligatori.',
    tc_isu_btn:       'Informazioni →',
    tc_nov_cat:       'Gare nazionali e internazionali',
    tc_nov_desc:      'Per atleti dagli 8 ai 15 anni con una buona tecnica di base (passo incrociato, trottole, piccoli salti, angeli) e disponibili ad allenarsi almeno 3 volte a settimana. Solo programma libero; 1-2 competizioni internazionali all\'anno. Stage estivo vivamente consigliato, stage tematici facoltativi.',
    tc_nov_btn:       'Informazioni →',
    tc_pj_cat:        'Pre-Agonismo',
    tc_pj_desc:       '<p class="tc-desc">Per atleti di qualsiasi età che abbiano terminato un corso di avviamento e vogliano un\'attività più intensiva. Ottima base per il sincronizzato e il solo dance.</p><p class="tc-desc" style="margin-top:.5rem;">Obiettivo: perfezionare la tecnica di pattinata, gli elementi artistici (salti e trottole) e la danza (fili, passi). Possibile impostazione di programmi per esibizioni.</p>',
    tc_pj_btn:        'Informazioni →',
    tc_juv_cat:       'Gare nazionali e internazionali',
    tc_juv_desc:      'Per atleti con una buona tecnica di base che vogliono crescere in un contesto agonistico strutturato. Programma libero; competizioni nazionali e internazionali. Stage estivo vivamente consigliato.',
    tc_juv_btn:       'Informazioni →',
    tc_ma_cat:        'Gare nazionali e internazionali',
    tc_ma_desc:       'Un\'opportunità per praticare una disciplina agonistica con impegno limitato e senza richieste tecniche vincolanti. È richiesta una buona pattinata di base. Solo programma libero, generazioni diverse insieme sul ghiaccio.',
    tc_ma_btn:        'Informazioni →',
    tc_adult_cat:     'Oltre 18 anni',
    tc_adult_desc:    'Il piacere di pattinare insieme a persone che condividono la propria passione, crescere come atleti e come persone, come una squadra. Un\'opportunità per chiunque voglia avvicinarsi a questa disciplina, a qualunque età e con qualunque livello tecnico. Anche per i genitori di un\'atleta! Solo programma libero.',
    tc_adult_btn:     'Informazioni →',
    tc_av_cat:        'Non agonistico',
    tc_av_desc:       'Il primo passo sul ghiaccio. Un percorso pensato per chi si avvicina al pattinaggio per la prima volta, con l\'obiettivo di acquisire le basi tecniche in un ambiente divertente, sicuro e stimolante.',
    tc_av_btn:        'Informazioni →',
    tc_avc_cat:       'Non agonistico',
    tc_avc_desc:      'Il piacere di pattinare a qualunque età e con qualunque livello tecnico. Un corso pensato per chi vuole imparare e migliorarsi, ma al momento non può prendere impegni agonistici.',
    tc_avc_btn:       'Informazioni →',
    tc_priv_cat:      'Allenamento individuale',
    tc_priv_desc:     'Lavoro one-to-one con i nostri tecnici. Ideale per chi vuole accelerare la propria crescita, affinare elementi specifici o prepararsi a un tryout. Disponibile per tutti i livelli.',
    tc_priv_btn:      'Prenota il tuo slot →',

    /* ── INDEX · RISULTATI ── */
    risultati_kicker:       'Risultati Gare',
    risultati_hero_h:       'Presenti ad ogni livello.<br>Stagione dopo stagione.',
    risultati_mondiali_lbl: 'Partecipazioni<br>ai Mondiali',
    risultati_intl_lbl:     'Competizioni<br>internazionali',
    risultati_vittorie_lbl: 'Vittorie nelle<br>ultime 2 stagioni',
    risultati_ticker_kicker:'Il circuito internazionale',
    risultati_ticker_h:     'Dove siamo state',
    risultati_crescita_kicker: 'Anno dopo anno',
    risultati_crescita_h:   'Una crescita che si vede nei numeri.',
    risultati_stagione_arr: 'stagione<br>in arrivo',
    risultati_podi_label:   'Podi complessivi per stagione · campionati nazionali e internazionali',
    risultati_quote:        '"La crescita più forte è arrivata negli anni più difficili. Perché una squadra vera si riconosce quando le cose non vanno come previsto."',
    risultati_agora_text:   'Dal gennaio 2023 Milano è senza il suo storico palazzetto del ghiaccio.',
    risultati_agora_link:   'La storia dell\'Agorà →',
    risultati_naz_kicker:   'Campionati italiani',
    risultati_naz_h:        'Presenti in ogni tappa, ogni anno.',
    risultati_naz_sub:      'Grazie a chi crede in noi.',
    risultati_2627_title:   'Stagione 2026·2027',
    risultati_2627_badge:   'In arrivo',
    risultati_2627_piste:   'Due piste dove allenarci!',
    risultati_pista1_lbl:   'Pista 1',
    risultati_pista2_lbl:   'Pista 2',
    risultati_san_donato:   'San Donato Milanese',
    risultati_rho:          'Rho · per avvicinarci a casa',
    risultati_grazie:       'Grazie per essere il ghiaccio su cui crescono i nostri sogni.',
    risultati_vedi:         'Vedi risultati ↓',
    risultati_intl_section: 'Competizioni internazionali',
    risultati_naz_section:  'Campionato nazionale',
    risultati_2526_title:   'Stagione 2025·2026',
    risultati_2425_title:   'Stagione 2024·2025',
    risultati_2324_title:   'Stagione 2023·2024',
    risultati_2223_title:   'Stagione 2022·2023',
    risultati_2122_title:   'Stagione 2021·2022',
    risultati_2021_title:   'Stagione 2020·2021',

    /* ── INDEX · NEWS ── */
    news_kicker:     'News / Eventi',
    news_h2:         'News &amp; Eventi',
    news_featured_tag:   'Breaking news · Pattinaggio sincronizzato',
    news_featured_title: 'Synchro 9 diventa<br><em>disciplina olimpica</em>',
    news_featured_p1:    'È ufficiale: il <strong>Synchro 9</strong>, la nuova disciplina ISU con squadre di 9 atleti, farà il suo debutto alle <strong>Olimpiadi Giovanili di Dolomiti Valtellina 2028</strong> e poi alle <strong>Olimpiadi Invernali Alpes 2030</strong>. Una svolta storica per tutto il pattinaggio sincronizzato mondiale.',
    news_featured_p2:    'Ladybirds è pronta: quest\'anno lanciamo le prime due squadre Synchro 9 (Junior e Senior). I nostri atleti saranno tra le protagoniste di questa nuova era.',
    news_pill3_d:    'Nuova disciplina ISU',
    news_pill3_t:    '9 atleti per team',
    news_ni1_tag:    'Iscrizioni',
    news_ni1_h4:     'Stagione 2026/2027 al via: 9 categorie in pista. Provini su appuntamento.',
    news_ni2_tag:    'Evento internazionale',
    news_ni2_h4:     'Milano Easter Trophy 2027: iscrizioni aperte per le squadre internazionali',
    news_ni3_tag:    'Stage',
    news_ni3_h4:     'Summer Camp 2026: ci vediamo sul ghiaccio questa estate',
    news_ni4_tag:    'Synchro 9',
    news_ni4_h4:     'Nasce il nuovo team Synchro 9 di Ladybirds, provini su appuntamento',

    /* ── INDEX · STAGES INLINE SECTION ── */
    stages_sec_kicker: 'Stages &amp; News',
    stages_sec_h2:     'Stages &amp; News',
    stages_intro1:  'Nel pattinaggio sincronizzato non ci si può nascondere. Sedici lame che si muovono insieme: se un piede è in ritardo di un centimetro, si vede. Se un angolo non è preciso, si vede. Questa disciplina costringe ogni atleta a raggiungere una precisione che nessun altro contesto riesce a richiedere con la stessa intensità.',
    stages_intro2:  'Per questo i nostri stage tematici sono aperti a <strong>chiunque voglia diventare più preciso sul ghiaccio</strong>: pattinatori artistici, danzatori su ghiaccio, atleti di qualsiasi livello e provenienza. Fare sincronizzato significa allenarsi alla perfezione. E quella perfezione si porta ovunque.',
    stages_intro3:  'Coach di livello internazionale, metodologie di alto livello, un ambiente serio e accogliente.',
    stages_tematici_kicker: 'Stage Tematici',

    /* ── INDEX · STAGES CARDS (shared con stages.html) ── */
    stc1_type:   'Stage multidisciplina · Artistico · Danza · Sincronizzato',
    stc1_title:  'Synchro Camp',
    stc1_sub:    '3 giorni per crescere e ispirarsi',
    stc1_desc:   'Aperto a pattinatori artistici, danzatori su ghiaccio e sincronizzato. Sei coach di livello internazionale per tre giorni di tecnica, coreografia, musicalità e master class. Con la special guest dalla Finlandia: Milja Sarkkinen.',
    stc1_guest_label: 'Special Guest',
    stc1_con_label:   'Con la partecipazione di',
    stc2_type:   'Stage tematico · Synchro 9',
    stc2_title:  'Stage con<br>Kaisa Arrateig',
    stc2_sub:    'La nuova avventura inizia da qui',
    stc2_desc:   'Quattro giorni dedicati alla nuova disciplina olimpica con una delle coach più esperte al mondo. Formazione squadre Senior Synchro 9 e Junior Synchro 9. Aperto anche ad atleti ISU.',
    stc_intro_day: 'Introduzione al Synchro 9',

    /* ── INDEX · CORVARA (shared) ── */
    corvara_kicker:  'Summer Camp · Corvara 2026',
    corvara_tag:     '12 – 26 Luglio 2026 · Alta Badia · Dolomiti',
    corvara_h3:      'Non è un ritiro.<br><em>È un laboratorio olimpico.</em>',
    corvara_desc:    'Il Summer Camp che prepara al futuro del pattinaggio. Synchro 9, precisione millimetrica, fili e transizioni. Con 9 atleti ogni dettaglio conta davvero.',
    corvara_guest_label:  'Special Guest · Finlandia',
    corvara_cristina_lbl: 'Power Skating',
    corvara_coreog:  'Coreografia e visione',
    corvara_ts_intl: 'TS International',
    corvara_riva_lbl:'Dettagli di gara',
    corvara_riva_role:'Ice Dance Coach',
    corvara_prep_lbl:'Preparazione e fluidità',
    corvara_posti:   'Posti limitati · tutte le categorie',
    corvara_btn:     'Richiedi informazioni →',

    /* ── INDEX · ISCRIZIONI ── */
    iscr_kicker:     'Iscrizioni e Moduli',
    iscr_h2:         'Entra a far parte<br>delle Ladybirds',
    iscr_provini_h4: 'Provini solo su appuntamento',
    iscr_provini_p:  'I provini per tutte le categorie si svolgono esclusivamente su appuntamento. Scrivici a info@ladybirds.it e ti ricontattiamo.',
    iscr_scrivici_kicker: 'Scrivici',
    iscr_scrivici_p: 'Per iscrizioni, provini e informazioni sulle categorie scrivici a:',

    /* ── INDEX · MY LMSA ── */
    lmsa_kicker:    'Area Riservata',
    lmsa_h2:        'MY LMSA',
    lmsa_p:         'Orari, quote, moduli e iscrizioni riservati alle famiglie degli atleti.',
    lmsa_psw_btn:   'Entra',
    lmsa_err:       'Password non corretta.',
    lmsa_iscr_kicker: 'Iscrizioni 2026–2027',
    lmsa_card1_title: 'Corsi <em>Non Agonismo</em>',
    lmsa_card1_desc:  'Corsi di avviamento al ghiaccio e pattinaggio amatoriale. Per bambini e adulti di tutti i livelli.',
    lmsa_card1_btn:   'Richiedi modulo e quote →',
    lmsa_card2_title: 'Agonismo <em>Sincronizzato</em>',
    lmsa_card2_desc:  'Stagione agonistica FISG 2026-2027.',
    lmsa_card2_btn:   '↓ Scarica modulo iscrizione',
    lmsa_card3_title: 'Agonismo <em>Adult Artistico</em>',
    lmsa_card3_desc:  'Pattinaggio artistico agonistico per adulti. Gare FISG categoria Adult Artistico.',
    lmsa_card3_btn:   'Richiedi modulo e quote →',
    lmsa_corvara_date: '12 – 26 Luglio 2026',
    lmsa_corvara_sub:  'Alta Badia · Dolomiti · In corso',
    lmsa_corvara_closed: 'Iscrizioni chiuse',
    lmsa_reg_kicker:  'Regolamenti e Moduli',
    lmsa_reg1_title:  'Regolamento',
    lmsa_reg1_desc:   'Regolamento Agonismo Sincronizzato Ladybirds Milano 2026-2027.',
    lmsa_reg1_btn:    '↓ Scarica PDF',
    lmsa_lib_title:   'Liberatoria Annuale',
    lmsa_lib_desc:    'Autorizzazione annuale a trasferte, pernottamenti e gestione delle emergenze.',
    lmsa_lib_btn:     '↓ Scarica PDF',
    lmsa_vis_title:   'Visita Agonistica',
    lmsa_vis_desc:    'Richiesta visita medico-sportiva per l\'idoneità alla pratica agonistica.',
    lmsa_vis_btn:     '↓ Scarica PDF',
    lmsa_ord_title:   'Ordine Divise',
    lmsa_ord_desc:    'Scegli le divise, seleziona taglie e quantità. Il totale viene calcolato in automatico.',
    lmsa_ord_btn:     '→ Compila ordine',
    lmsa_contacts_title: 'Contatti',
    lmsa_modal_title: 'Scrivici per informazioni',
    lmsa_modal_btn:   '✉ Scrivi a info@ladybirds.it →',

    /* ── FOOTER (tutti) ── */
    footer_sub:        'Milano Synchro Academy A.S.D.',
    footer_cf:         'CF 97846210157 · Dona il 5×1000',
    footer_cf_suffix:  'Dona il 5×1000',
    footer_pagine:     'Pagine',
    footer_piste:      'Piste',
    footer_competizioni: 'Competizioni',
    footer_contatti:   'Contatti',
    footer_copy:       '© 2026 Ladybirds Milano Synchro Academy A.S.D. · Tutti i diritti riservati',

    /* ── STAGES.HTML ── */
    stages_hero_h1:   'Stage &amp; <em>Camp</em>',
    stages_hero_sub:  'Coach di livello internazionale. Per chi vuole diventare davvero preciso sul ghiaccio, qualunque sia la propria disciplina.',
    stages_pill1:     'Sincronizzato',
    stages_pill2:     'Pattinaggio Artistico',
    stages_pill3:     'Danza su Ghiaccio',
    stages_bread:     'Stage &amp; Camp',
    stages_full_tematici_kicker: 'Stage Tematici',
    stages_s9_type:   'Nuova disciplina olimpica · 3 giorni',
    stages_s9_title:  'Introduzione al<br>Synchro 9',
    stages_s9_coach_lbl: 'Coach',
    stages_s9_aperto_lbl: 'Aperto a',
    stages_s9_desc:   'Il Synchro 9 è la nuova disciplina olimpica del pattinaggio sincronizzato: nove atleti, tecnica di altissimo livello, piena libertà coreografica. Tre giorni per scoprire come si allena, si costruisce e si compete con coach di livello mondiale.',
    stages_s9_posti:  'Posti limitati',
    stages_s9_scad:   'Iscrizione entro il 2 Maggio',
    stages_s9_btn:    'Richiedi informazioni →',
    stages_ka_type:   'Synchro 9 · Perfezionamento · 4 giorni',
    stages_ka_title:  'Synchro 9<br>Development',
    stages_ka_sub:    'con Kaisa Arrateig',
    stages_ka_desc:   'Quattro giorni intensivi per portare il Synchro 9 al livello successivo. Formazioni, precisione millimetrica, identità di squadra e visione coreografica con una delle coach più titolate al mondo.',
    stages_ka_posti:  'Posti limitati',
    stages_ka_scad:   'Iscrizione entro il 7 Giugno',
    stages_ka_btn:    'Richiedi informazioni →',
    stages_corvara_kicker: 'Summer Camp · Corvara 2026',
    stages_corvara_tag:    '12 – 26 Luglio 2026 · Alta Badia · Dolomiti',
    stages_corvara_h3:     'Corvara è dove comincia<br><em>la tua prossima stagione.</em>',
    stages_corvara_desc1:  'Corvara non è una settimana di allenamenti da aggiungere al calendario. È un percorso intensivo in cui ghiaccio, preparazione atletica, tecnica, coreografia e lavoro individuale e di squadra si fondono in un unico progetto di crescita.',
    stages_corvara_desc2:  'Ogni atleta viene accompagnato a superare abitudini, limiti e automatismi, con coach qualificati, competenze internazionali e un focus speciale sul Synchro 9.',
    stages_corvara_desc3:  'Non si viene a Corvara per mantenersi in forma.<br>Si viene per tornare diversi.',
    stages_corvara_guest_lbl: 'Special Guest · Finlandia',
    stages_corvara_milja_role: 'Coreografia e visione',
    stages_corvara_psk_lbl:    'Power Skating',
    stages_corvara_cristina_role: 'TS International',
    stages_corvara_pattinaggio_lbl: 'Tecnica di Pattinaggio',
    stages_corvara_riva_role:  'Tecnico · Tecnica di pattinata',
    stages_corvara_artistico_lbl: 'Pattinaggio Artistico',
    stages_corvara_marina_role: 'Insegnante di Artistico',
    stages_corvara_prep_lbl:   'Preparazione Atletica',
    stages_corvara_ales_role:  'Preparatore Atletico · Massofisioterapista',
    stages_corvara_posti_info: 'Posti limitati · focus Synchro 9',
    stages_corvara_btn:        'Richiedi informazioni →',
    stages_cta_kicker:  'Prossimi stage',
    stages_cta_h3:      'Sei interessato a sapere in anticipo<br>i prossimi stage?',
    stages_cta_p:       'Tieni d\'occhio la pagina News e rimani aggiornato. I posti si esauriscono in fretta. Non perdere le prossime occasioni.',
    stages_cta_news_btn: 'Vai alle News →',
    stages_cta_wa_btn:   'Scrivici su WhatsApp',
    stages_footer_cf:    'CF 97846210157 · Dona il 5×1000',

    /* ── NEWS.HTML ── */
    news_hero_h1:    'News &amp; <em>Novità</em>',
    news_hero_sub:   'La vita di una squadra si racconta una storia alla volta.',
    news_prossimamente_kicker: 'Prossimamente',
    news_in_arrivo_label: 'Stage &amp; Camp in arrivo',
    news_in_arrivo_h2:    'I prossimi appuntamenti sul ghiaccio',
    news_in_arrivo_sub:   'I posti si esauriscono in fretta. Tieni d\'occhio questa pagina.',
    news_corvara_name:    'Corvara Summer Camp 2026',
    news_corvara_date:    '12 – 26 Luglio 2026 · Alta Badia, Dolomiti · Aperto a tutte le categorie',
    news_corvara_badge:   'Iscrizioni chiuse',
    news_prossimo_name:   'Prossimo stage · Autunno 2026',
    news_prossimo_date:   'Data e dettagli in definizione',
    news_prossimo_badge:  'In arrivo',
    news_calendario_kicker: 'Calendario Gare 2026–2027',
    news_calendario_p:   'Dove gareggeranno le Ladybirds, mese per mese. Aggiornato con le date FISG.',
    news_cal_empty:       'In attesa di calendario FISG',
    news_stage_kicker:   'Stage 2026',
    news_nc1_tag:        'Stage · Sold Out',
    news_nc1_title:      'Introduzione al Synchro 9 con Milja Sarkkinen: posti esauriti',
    news_nc1_excerpt:    'Il primo stage italiano dedicato al Synchro 9 ha fatto il tutto esaurito in pochi giorni. Tre giorni intensivi, sei coach internazionali, un\'esperienza che ha cambiato il modo di vedere la disciplina.',
    news_nc1_cta:        'Vedi i prossimi stage →',
    news_nc2_tag:        'Stage · Sold Out',
    news_nc2_title:      'Synchro 9 Development con Kaisa Arrateig: anche questo sold out',
    news_nc2_excerpt:    'Quattro giorni con la Head Coach delle Helsinki Rockettes. 4× World Champion Coach. Formazioni, precisione, identità di squadra. Un\'esperienza che si ripete.',
    news_nc2_cta:        'Vedi i prossimi stage →',
    news_nc3_tag:        'Synchro 9',
    news_nc3_title:      'Il Synchro 9 diventa olimpico. Noi lo stavamo già allenando.',
    news_nc3_excerpt:    'Il 7 luglio 2026 il Synchro 9 entra ufficialmente nel programma olimpico. Le Ladybirds avevano già iniziato: stage dedicati, coach internazionali, una squadra in crescita. Quando gli altri hanno scoperto questa disciplina, noi eravamo già sul ghiaccio.',
    news_nc3_cta:        'Scopri il Synchro 9 →',
    news_evidenza_kicker: 'In evidenza',
    news_festa_tag:      'Festa di Fine Anno · 25 Maggio 2026',
    news_festa_p:        'Grazie alle atlete, ai genitori, allo staff, all\'Accademia del Ghiaccio e a TUTTI coloro che hanno reso possibile ogni prova, ogni sorriso, ogni emozione sul ghiaccio. Senza di voi, nulla sarebbe stato lo stesso.',
    news_stagione_kicker: 'Stagione 2025–2026',
    news_wide_tag:       'Risultati',
    news_wide_title:     'Una stagione da record. Le Ladybirds non si fermano.',
    news_wide_excerpt:   'Podio dopo podio, gara dopo gara. Le nostre squadre hanno disputato una stagione straordinaria raccogliendo risultati che testimoniano anni di lavoro, dedizione e spirito di squadra. Dal Pre-Juvenile al Junior Isu, ogni categoria ha lasciato il segno sul ghiaccio italiano.',
    news_wide_cta:       'Vedi tutti i risultati →',
    news_med_tag:        'Risultati',
    news_med_title:      'Le piccole Ladybirds crescono: podi ai campionati giovanili',
    news_med_excerpt:    'Le giovani pattinatrici hanno dimostrato il loro valore nelle categorie giovanili. Medaglie, sorrisi e la consapevolezza di far parte di qualcosa di grande. Il futuro delle Ladybirds è in buone mani.',
    news_met_tag:        'Milano Easter Trophy',
    news_met_title:      'Milano Easter Trophy 2026: il ghiaccio di casa, il pubblico di tutta Europa',
    news_met_excerpt:    'La competizione internazionale organizzata dalle Ladybirds. Squadre da tutta Europa, emozioni, musica e il meglio del pattinaggio sincronizzato al Palazzo del Ghiaccio.',
    news_met_cta:        'Vai al sito del Trophy →',
    news_archivio_kicker: 'Archivio',
    news_mondiali_tag:   'Mondiali',
    news_mondiali_title: 'Anche le Ladybirds arrivano ai Mondiali',
    news_mondiali_excerpt: 'Neuchâtel e Gothenburg. Un traguardo che sembrava lontano, poi sempre più vicino, poi realtà. Le nostre ragazze sul ghiaccio di una competizione mondiale: le emozioni di chi ce l\'ha fatta davvero.',
    news_salone_tag:     'Club',
    news_salone_title:   'Le Ladybirds nella campagna ufficiale di Visit Milano per la Design Week',
    news_salone_excerpt: 'Scelte da Visit Milano e dal Salone del Mobile per rappresentare la città durante la Milano Design Week. Le nostre atlete in pattini alla Stazione Centrale, con il logo olimpico. Una storia che racconta chi siamo.',
    news_salone_cta:     'Vedi il post →',

    /* ── ORDINE-DIVISE.HTML ── */
    order_nav_back:    '← Sito',
    order_hero_h1:     'Ordine Divise · Stagione 2026–2027',
    order_hero_p:      'Compila il modulo, controlla il totale e invia l\'ordine via email',
    order_referente:   'Referente: <strong>Liana</strong>',
    order_tel:         'Tel. <strong>338 696 9823</strong> (dopo le 18:00)',
    order_total_lbl:   'Totale stimato',
    order_dati_title:  'Dati Atleta / Genitore',
    order_atleta_lbl:  'Nome e cognome atleta *',
    order_genitore_lbl:'Nome genitore / tutore',
    order_email_lbl:   'Email *',
    order_tel_lbl:     'Telefono',
    order_legend1:     '<span class="star">★</span> Obbligatorio per Agonismo Sincronizzato',
    order_legend2:     '<span class="star">★★★</span> Obbligatorio per Corsi Avviamento',
    order_note_title:  'Note / Richieste particolari',
    order_subtotal_title: 'Riepilogo ordine',
    order_subtotal_tot:   'Totale stimato <span class="note">* da confermare</span>',
    order_submit_btn:  '✉ Invia ordine a Ladybirds',
    order_submit_note: 'Il totale è una stima. Verrai contattato entro 2-3 giorni lavorativi per conferma disponibilità e pagamento.',
    order_confirm_h2:  'Ordine pronto!',
    order_confirm_p1:  'Il tuo client email si aprirà con l\'ordine già compilato per <strong>divise@ladybirds.it</strong>.',
    order_confirm_warn:'⚠️ Il totale è <strong>stimato</strong>. Riceverai conferma di disponibilità e importo definitivo entro <strong>2–3 giorni lavorativi</strong>.',
    order_confirm_btn: '📄 Scarica PDF e apri email',
    order_confirm_cancel: '← Torna al modulo',
  },

  en: {
    /* ── NAV ── */
    nav_home:        'Home',
    nav_staff:       'Staff',
    nav_teams:       'Teams 2026–2027',
    nav_risultati:   'Competition Results',
    nav_stage:       'Stage &amp; Camp',
    nav_news:        'News',
    nav_lmsa:        'MY LMSA',

    /* ── INDEX · HERO ── */
    hero_eyebrow:    'Milan · Synchro Academy · Since 1998',
    hero_h1:         'Synchronized<br>Skating<br>in <em>Milan</em>',
    hero_claim:      'Italy\'s largest synchronized skating club',
    hero_p:          'From first blades on ice to international stages — multiple categories for every age and level.',
    hero_btn_iscr:   'Join 2026/2027',

    /* ── INDEX · CHI SIAMO ── */
    chi_kicker:      'About us',
    chi_h2:          'Born in 1998,<br>grown on the ice of Milan',
    chi_p1:          'Synchronized skating is a spectacular discipline requiring great coordination and harmony among athletes. It is a team sport combining the grace of figure skating with choreographed movements performed in unison. Participation helps develop cooperation, communication and mutual trust among team members.',
    chi_p2:          'Founded in 1998, <strong>Ladybirds Milano Synchro Academy</strong> is a centre of excellence in synchronized skating in Italy, contributing to the growth and spread of this sport throughout the country.',

    /* ── INDEX · FORMAZIONE ── */
    form_kicker:     'Training &amp; levels',
    form_h3:         'A sport for<br>every level and every age',
    form_p1:         'Through structured and personalised programmes, we guide each athlete on a complete growth journey where technique, artistry and expressiveness come together on the ice.',
    form_p2:         'Open to athletes of every level: from those taking their first steps on the ice to competitive skaters, including those from dance, figure skating or other disciplines.',
    form_p3:         'Each team is formed taking into account age, experience and technical ability, to offer every athlete a progressive and stimulating pathway.',

    /* ── INDEX · COMPETIZIONI ── */
    comp_kicker:     'Competitions &amp; events',
    comp_h3:         'On the ice<br>and on the world\'s stages',
    comp_p1:         'Beyond competitive activity, our club promotes synchronized skating through events, exhibitions and national and international competitions.',
    comp_p2:         'Among these, we organise the <strong style="color:var(--navy);">Milano Easter Trophy</strong>, an international event that brings teams and athletes from around the world to Milan, offering an important opportunity for sport, exchange and growth.',
    comp_met_link:   'Visit milanoeastertrophy.it →',

    /* ── INDEX · OBIETTIVI ── */
    obiet_kicker:    'Educational &amp; social goals',
    obiet_h3:        'Growing together,<br>on and off the ice',
    obiet_p1:        'At Ladybirds Milano Synchro Academy, sport is a personal growth journey. Through synchronized skating we instil values such as teamwork, discipline, resilience and determination.',
    obiet_p2:        'Our Academy offers a positive, inclusive and stimulating environment where every athlete grows as a person.',

    /* ── INDEX · STAGES BLOCK ── */
    stages_kicker:   'Camps',
    stages_h3:       'Stage &amp; Camp',
    stages_p:        'The Academy organises themed camps open to athletes from other disciplines too: special opportunities to deepen technique, find new inspiration and grow together in a dynamic, educational and exciting environment.',
    stages_link:     'Next event info →',

    /* ── INDEX · 5x1000 ── */
    cinquemila_kicker:  'Costs you nothing',
    cinquemila_h3:      'Donate your<br><em style="color:var(--gold);font-style:italic;">5×1000</em>',
    cinquemila_p:       'In your tax return, under the section <strong style="color:#fff;">«Support for volunteering and other non-profit organisations»</strong>, enter our tax code. A simple gesture that makes a real difference for our athletes.',

    /* ── INDEX · SOSTIENI ── */
    sostieni_kicker:    'Support Ladybirds',
    sostieni_h3:        'Your support makes the difference',
    sostieni_p1:        'Taking a team to compete abroad has a real cost: travel, competition costumes, camps with international coaches, championship entry fees. Without support these costs fall entirely on the athletes\' families.',
    sostieni_p2:        'Supporting Ladybirds means lightening that burden and allowing talented athletes to keep dreaming and competing at the highest level, regardless of their family\'s financial means.',
    sostieni_btn_partner: 'Become a partner →',
    sostieni_btn_sponsor: 'Become a sponsor →',

    /* ── INDEX · STAFF ── */
    staff_kicker:       'Technical Staff',
    staff_h2:           'Our coaching<br>team',
    staff_p:            'An international staff of the highest calibre: coaches, trainers, athletic coaches and specialists working together to help every athlete grow, on and off the ice.',
    staff_dir_title:    'Technical Direction',
    staff_dir_role:     'Technical Director &amp; Head Coach',
    staff_dir_desc:     'Technical leadership and overall vision for the entire Ladybirds programme. Responsible for squad development and every athlete\'s growth.',
    staff_cons_title:   'International Consultants',
    staff_pascal_role:  'International consultant · Synchronized skating',
    staff_roberto_role: 'External consultant · Skating technique',
    staff_tech_title:   'Technical Staff',
    staff_support_title: 'Support Staff',

    /* ── INDEX · TEAMS ── */
    teams_kicker:     'Squads',
    teams_h2:         'Teams 2026·2027',
    tc_s9_cat:        'New Olympic discipline',
    tc_s9_desc:       '<p class="tc-desc">9 athletes. A completely new format: head-to-head challenges, elimination rounds, themed performances. Faster, more dynamic, designed for today\'s audience.</p><p class="tc-desc" style="margin-top:.5rem;">The Junior team will debut at the 2028 Youth Olympics in Italy (Dolomiti Valtellina). The Senior team at the 2030 Winter Olympics in the Alps. Ladybirds is building both teams now.</p><p class="tc-desc" style="margin-top:.5rem;">If you have solid experience in synchronized or figure skating, this is your chance to be part of a story that is just beginning. <strong>Tryout required. Limited spots.</strong></p>',
    tc_s9_btn:        'More info →',
    tc_isu_cat:       'ISU · International competitions',
    tc_isu_desc:      'Athletes must pass an internal selection test (twizzles, step sequences, jumps, spirals, edges, spins). Short and free programme; 2–4 international competitions per year. Summer camp and themed camps mandatory.',
    tc_isu_btn:       'More info →',
    tc_nov_cat:       'National &amp; international competitions',
    tc_nov_desc:      'For athletes aged 8–15 with a good basic technique (crossovers, spins, small jumps, spirals) willing to train at least 3 times a week. Free programme only; 1–2 international competitions per year. Summer camp strongly recommended, themed camps optional.',
    tc_nov_btn:       'More info →',
    tc_pj_cat:        'Pre-competitive',
    tc_pj_desc:       '<p class="tc-desc">For athletes of any age who have completed a beginner course and want more intensive training. An excellent foundation for synchronized skating and solo dance.</p><p class="tc-desc" style="margin-top:.5rem;">Goal: refine skating technique, artistic elements (jumps and spins) and dance (edges, steps). Exhibition programmes may be set up.</p>',
    tc_pj_btn:        'More info →',
    tc_juv_cat:       'National &amp; international competitions',
    tc_juv_desc:      'For athletes with a good basic technique who want to grow in a structured competitive environment. Free programme; national and international competitions. Summer camp strongly recommended.',
    tc_juv_btn:       'More info →',
    tc_ma_cat:        'National &amp; international competitions',
    tc_ma_desc:       'An opportunity to practise competitive skating with limited commitment and no binding technical requirements. A good basic skating level is required. Free programme only — different generations on the ice together.',
    tc_ma_btn:        'More info →',
    tc_adult_cat:     '18 years and over',
    tc_adult_desc:    'The pleasure of skating with people who share your passion, growing as athletes and as people, as a team. An opportunity for anyone who wants to approach this discipline, at any age and at any technical level — even a skater\'s parents! Free programme only.',
    tc_adult_btn:     'More info →',
    tc_av_cat:        'Non-competitive',
    tc_av_desc:       'The first step on ice. A programme designed for those approaching skating for the first time, with the goal of acquiring basic technique in a fun, safe and stimulating environment.',
    tc_av_btn:        'More info →',
    tc_avc_cat:       'Non-competitive',
    tc_avc_desc:      'The pleasure of skating at any age and at any technical level. A course designed for those who want to learn and improve, but cannot currently commit to competitive skating.',
    tc_avc_btn:       'More info →',
    tc_priv_cat:      'Individual training',
    tc_priv_desc:     'One-to-one sessions with our coaches. Ideal for those who want to accelerate their progress, refine specific elements or prepare for a tryout. Available for all levels.',
    tc_priv_btn:      'Book your slot →',

    /* ── INDEX · RISULTATI ── */
    risultati_kicker:       'Competition Results',
    risultati_hero_h:       'Present at every level.<br>Season after season.',
    risultati_mondiali_lbl: 'World<br>Championship appearances',
    risultati_intl_lbl:     'International<br>competitions',
    risultati_vittorie_lbl: 'Wins in the<br>last 2 seasons',
    risultati_ticker_kicker:'The international circuit',
    risultati_ticker_h:     'Where we\'ve competed',
    risultati_crescita_kicker: 'Year after year',
    risultati_crescita_h:   'Growth you can see in the numbers.',
    risultati_stagione_arr: 'season<br>coming soon',
    risultati_podi_label:   'Podiums per season · national and international championships',
    risultati_quote:        '"The strongest growth came in the hardest years. Because a true team shows itself when things don\'t go as planned."',
    risultati_agora_text:   'Since January 2023 Milan has been without its historic ice rink.',
    risultati_agora_link:   'The Agorà story →',
    risultati_naz_kicker:   'Italian Championships',
    risultati_naz_h:        'Present at every stage, every year.',
    risultati_naz_sub:      'Thanks to those who believe in us.',
    risultati_2627_title:   'Season 2026·2027',
    risultati_2627_badge:   'Coming soon',
    risultati_2627_piste:   'Two rinks to train on!',
    risultati_pista1_lbl:   'Rink 1',
    risultati_pista2_lbl:   'Rink 2',
    risultati_san_donato:   'San Donato Milanese',
    risultati_rho:          'Rho · closer to home',
    risultati_grazie:       'Thank you for being the ice on which our dreams grow.',
    risultati_vedi:         'See results ↓',
    risultati_intl_section: 'International competitions',
    risultati_naz_section:  'National championship',
    risultati_2526_title:   'Season 2025·2026',
    risultati_2425_title:   'Season 2024·2025',
    risultati_2324_title:   'Season 2023·2024',
    risultati_2223_title:   'Season 2022·2023',
    risultati_2122_title:   'Season 2021·2022',
    risultati_2021_title:   'Season 2020·2021',

    /* ── INDEX · NEWS ── */
    news_kicker:     'News / Events',
    news_h2:         'News &amp; Events',
    news_featured_tag:   'Breaking news · Synchronized skating',
    news_featured_title: 'Synchro 9 becomes<br><em>an Olympic discipline</em>',
    news_featured_p1:    'It\'s official: <strong>Synchro 9</strong>, the new ISU discipline with 9-athlete teams, will make its debut at the <strong>2028 Youth Olympics in Dolomiti Valtellina</strong> and then at the <strong>2030 Winter Olympics in the Alps</strong>. A historic turning point for synchronized skating worldwide.',
    news_featured_p2:    'Ladybirds is ready: this year we are launching the first two Synchro 9 teams (Junior and Senior). Our athletes will be among the protagonists of this new era.',
    news_pill3_d:    'New ISU discipline',
    news_pill3_t:    '9 athletes per team',
    news_ni1_tag:    'Registrations',
    news_ni1_h4:     'Season 2026/2027 underway: 9 categories on the ice. Tryouts by appointment.',
    news_ni2_tag:    'International event',
    news_ni2_h4:     'Milano Easter Trophy 2027: registrations open for international teams',
    news_ni3_tag:    'Camp',
    news_ni3_h4:     'Summer Camp 2026: see you on the ice this summer',
    news_ni4_tag:    'Synchro 9',
    news_ni4_h4:     'The new Ladybirds Synchro 9 team is born — tryouts by appointment',

    /* ── INDEX · STAGES INLINE SECTION ── */
    stages_sec_kicker: 'Stages &amp; News',
    stages_sec_h2:     'Stages &amp; News',
    stages_intro1:  'In synchronized skating there is nowhere to hide. Many blades moving as one: if a foot is a centimetre late, it shows. If an angle is not precise, it shows. This discipline forces every athlete to reach a level of precision that no other setting can demand with the same intensity.',
    stages_intro2:  'That is why our themed camps are open to <strong>anyone who wants to become more precise on the ice</strong>: figure skaters, ice dancers, athletes of any level and background. Training in synchronised skating means training for perfection — and that perfection stays with you everywhere.',
    stages_intro3:  'International-level coaches, top-level methodologies, a serious and welcoming environment.',
    stages_tematici_kicker: 'Thematic Camps',

    /* ── INDEX · STAGES CARDS ── */
    stc1_type:   'Multi-discipline camp · Figure · Dance · Synchro',
    stc1_title:  'Synchro Camp',
    stc1_sub:    '3 days to grow and be inspired',
    stc1_desc:   'Open to figure skaters, ice dancers and synchronized skaters. Six international-level coaches for three days of technique, choreography, musicality and master classes. Featuring special guest from Finland: Milja Sarkkinen.',
    stc1_guest_label: 'Special Guest',
    stc1_con_label:   'With the participation of',
    stc2_type:   'Thematic camp · Synchro 9',
    stc2_title:  'Stage with<br>Kaisa Arrateig',
    stc2_sub:    'The new adventure starts here',
    stc2_desc:   'Four days dedicated to the new Olympic discipline with one of the most experienced coaches in the world. Formation of Senior Synchro 9 and Junior Synchro 9 teams. Also open to ISU athletes.',
    stc_intro_day: 'Introduction to Synchro 9',

    /* ── INDEX · CORVARA ── */
    corvara_kicker:  'Summer Camp · Corvara 2026',
    corvara_tag:     '12 – 26 July 2026 · Alta Badia · Dolomites',
    corvara_h3:      'Not a training retreat.<br><em>An Olympic laboratory.</em>',
    corvara_desc:    'The Summer Camp that prepares you for the future of skating. Synchro 9, millimetre precision, edges and transitions. With 9 athletes every detail truly matters.',
    corvara_guest_label:  'Special Guest · Finland',
    corvara_cristina_lbl: 'Power Skating',
    corvara_coreog:  'Choreography and vision',
    corvara_ts_intl: 'TS International',
    corvara_riva_lbl:'Competition details',
    corvara_riva_role:'Ice Dance Coach',
    corvara_prep_lbl:'Preparation &amp; fluidity',
    corvara_posti:   'Limited spots · all categories',
    corvara_btn:     'Request information →',

    /* ── INDEX · ISCRIZIONI ── */
    iscr_kicker:     'Registrations &amp; Forms',
    iscr_h2:         'Join<br>the Ladybirds',
    iscr_provini_h4: 'Tryouts by appointment only',
    iscr_provini_p:  'Tryouts for all categories are held by appointment only. Write to us at info@ladybirds.it and we will get back to you.',
    iscr_scrivici_kicker: 'Contact us',
    iscr_scrivici_p: 'For registrations, tryouts and category information, write to us at:',

    /* ── INDEX · MY LMSA ── */
    lmsa_kicker:    'Members Area',
    lmsa_h2:        'MY LMSA',
    lmsa_p:         'Schedules, fees, forms and registrations reserved for athletes\' families.',
    lmsa_psw_btn:   'Enter',
    lmsa_err:       'Incorrect password.',
    lmsa_iscr_kicker: 'Registrations 2026–2027',
    lmsa_card1_title: 'Non-Competitive <em>Courses</em>',
    lmsa_card1_desc:  'Beginner and recreational skating courses. For children and adults of all levels.',
    lmsa_card1_btn:   'Request form &amp; fees →',
    lmsa_card2_title: 'Competitive <em>Synchro</em>',
    lmsa_card2_desc:  'FISG competitive season 2026-2027.',
    lmsa_card2_btn:   '↓ Download registration form',
    lmsa_card3_title: 'Competitive <em>Adult Figure</em>',
    lmsa_card3_desc:  'Competitive figure skating for adults. FISG Adult Figure category competitions.',
    lmsa_card3_btn:   'Request form &amp; fees →',
    lmsa_corvara_date: '12 – 26 July 2026',
    lmsa_corvara_sub:  'Alta Badia · Dolomites · In progress',
    lmsa_corvara_closed: 'Registrations closed',
    lmsa_reg_kicker:  'Rules &amp; Forms',
    lmsa_reg1_title:  'Rules',
    lmsa_reg1_desc:   'Ladybirds Milano Synchro Competitive Rules 2026-2027.',
    lmsa_reg1_btn:    '↓ Download PDF',
    lmsa_lib_title:   'Annual Consent Form',
    lmsa_lib_desc:    'Annual authorisation for travel, overnight stays and emergency management.',
    lmsa_lib_btn:     '↓ Download PDF',
    lmsa_vis_title:   'Medical Certificate',
    lmsa_vis_desc:    'Request for sports medical examination for competitive eligibility.',
    lmsa_vis_btn:     '↓ Download PDF',
    lmsa_ord_title:   'Uniform Order',
    lmsa_ord_desc:    'Choose uniforms, select sizes and quantities. Total is calculated automatically.',
    lmsa_ord_btn:     '→ Fill in order',
    lmsa_contacts_title: 'Contacts',
    lmsa_modal_title: 'Write to us for information',
    lmsa_modal_btn:   '✉ Write to info@ladybirds.it →',

    /* ── FOOTER ── */
    footer_sub:        'Milan Synchro Academy A.S.D.',
    footer_cf:         'Tax code 97846210157 · Donate your 5×1000',
    footer_cf_suffix:  'Donate your 5×1000',
    footer_pagine:     'Pages',
    footer_piste:      'Rinks',
    footer_competizioni: 'Competitions',
    footer_contatti:   'Contacts',
    footer_copy:       '© 2026 Ladybirds Milano Synchro Academy A.S.D. · All rights reserved',

    /* ── STAGES.HTML ── */
    stages_hero_h1:   'Stage &amp; <em>Camp</em>',
    stages_hero_sub:  'International-level coaches. For those who want to become truly precise on ice, whatever their discipline.',
    stages_pill1:     'Synchronized',
    stages_pill2:     'Figure Skating',
    stages_pill3:     'Ice Dance',
    stages_bread:     'Stage &amp; Camp',
    stages_full_tematici_kicker: 'Thematic Camps',
    stages_s9_type:   'New Olympic discipline · 3 days',
    stages_s9_title:  'Introduction to<br>Synchro 9',
    stages_s9_coach_lbl: 'Coach',
    stages_s9_aperto_lbl: 'Open to',
    stages_s9_desc:   'Synchro 9 is the new Olympic discipline of synchronized skating: nine athletes, extremely high-level technique, complete choreographic freedom. Three days to discover how it is trained, built and competed with world-class coaches.',
    stages_s9_posti:  'Limited spots',
    stages_s9_scad:   'Registration by 2 May',
    stages_s9_btn:    'Request information →',
    stages_ka_type:   'Synchro 9 · Advanced · 4 days',
    stages_ka_title:  'Synchro 9<br>Development',
    stages_ka_sub:    'with Kaisa Arrateig',
    stages_ka_desc:   'Four intensive days to take Synchro 9 to the next level. Formations, millimetre precision, team identity and choreographic vision with one of the most decorated coaches in the world.',
    stages_ka_posti:  'Limited spots',
    stages_ka_scad:   'Registration by 7 June',
    stages_ka_btn:    'Request information →',
    stages_corvara_kicker: 'Summer Camp · Corvara 2026',
    stages_corvara_tag:    '12 – 26 July 2026 · Alta Badia · Dolomites',
    stages_corvara_h3:     'Corvara is where<br><em>your next season begins.</em>',
    stages_corvara_desc1:  'Corvara is not a week of training to add to the calendar. It is an intensive programme where ice, athletic preparation, technique, choreography and individual and team work merge into a single growth project.',
    stages_corvara_desc2:  'Each athlete is guided to overcome habits, limits and automatisms, with qualified coaches, international expertise and a special focus on Synchro 9.',
    stages_corvara_desc3:  'You don\'t come to Corvara to stay in shape.<br>You come to leave different.',
    stages_corvara_guest_lbl: 'Special Guest · Finland',
    stages_corvara_milja_role: 'Choreography and vision',
    stages_corvara_psk_lbl:    'Power Skating',
    stages_corvara_cristina_role: 'TS International',
    stages_corvara_pattinaggio_lbl: 'Skating Technique',
    stages_corvara_riva_role:  'Coach · Skating technique',
    stages_corvara_artistico_lbl: 'Figure Skating',
    stages_corvara_marina_role: 'Figure Skating Teacher',
    stages_corvara_prep_lbl:   'Athletic Training',
    stages_corvara_ales_role:  'Athletic Trainer · Sports Physiotherapist',
    stages_corvara_posti_info: 'Limited spots · Synchro 9 focus',
    stages_corvara_btn:        'Request information →',
    stages_cta_kicker:  'Upcoming camps',
    stages_cta_h3:      'Want to be notified about<br>upcoming camps in advance?',
    stages_cta_p:       'Keep an eye on the News page and stay updated. Spots fill up fast. Don\'t miss the next opportunities.',
    stages_cta_news_btn: 'Go to News →',
    stages_cta_wa_btn:   'Message us on WhatsApp',
    stages_footer_cf:    'Tax code 97846210157 · Donate your 5×1000',

    /* ── NEWS.HTML ── */
    news_hero_h1:    'News &amp; <em>Updates</em>',
    news_hero_sub:   'A team\'s life is told one story at a time.',
    news_prossimamente_kicker: 'Coming up',
    news_in_arrivo_label: 'Upcoming Stage &amp; Camp',
    news_in_arrivo_h2:    'Upcoming ice events',
    news_in_arrivo_sub:   'Spots fill up fast. Keep an eye on this page.',
    news_corvara_name:    'Corvara Summer Camp 2026',
    news_corvara_date:    '12 – 26 July 2026 · Alta Badia, Dolomites · Open to all categories',
    news_corvara_badge:   'Registrations closed',
    news_prossimo_name:   'Next camp · Autumn 2026',
    news_prossimo_date:   'Date and details to be confirmed',
    news_prossimo_badge:  'Coming soon',
    news_calendario_kicker: 'Competition Calendar 2026–2027',
    news_calendario_p:   'Where Ladybirds will compete, month by month. Updated with FISG dates.',
    news_cal_empty:       'Awaiting FISG calendar',
    news_stage_kicker:   'Camps 2026',
    news_nc1_tag:        'Camp · Sold Out',
    news_nc1_title:      'Introduction to Synchro 9 with Milja Sarkkinen: sold out',
    news_nc1_excerpt:    'The first Italian camp dedicated to Synchro 9 sold out in just a few days. Three intensive days, six international coaches, an experience that changed the way this discipline is seen.',
    news_nc1_cta:        'See upcoming camps →',
    news_nc2_tag:        'Camp · Sold Out',
    news_nc2_title:      'Synchro 9 Development with Kaisa Arrateig: also sold out',
    news_nc2_excerpt:    'Four days with the Head Coach of the Helsinki Rockettes. 4× World Champion Coach. Formations, precision, team identity. An experience that repeats itself.',
    news_nc2_cta:        'See upcoming camps →',
    news_nc3_tag:        'Synchro 9',
    news_nc3_title:      'Synchro 9 becomes Olympic. We were already training it.',
    news_nc3_excerpt:    'On 7 July 2026 Synchro 9 officially entered the Olympic programme. Ladybirds had already begun: dedicated camps, international coaches, a growing team. When others discovered this discipline, we were already on the ice.',
    news_nc3_cta:        'Discover Synchro 9 →',
    news_evidenza_kicker: 'Featured',
    news_festa_tag:      'End-of-Year Celebration · 25 May 2026',
    news_festa_p:        'Thank you to the athletes, parents, staff, the ice rink and EVERYONE who made every session, every smile and every emotion on the ice possible. Without you, none of it would have been the same.',
    news_stagione_kicker: 'Season 2025–2026',
    news_wide_tag:       'Results',
    news_wide_title:     'A record-breaking season. Ladybirds keep on going.',
    news_wide_excerpt:   'Podium after podium, competition after competition. Our teams delivered an extraordinary season with results that testify to years of work, dedication and team spirit. From Pre-Juvenile to Junior ISU, every category left its mark on Italian ice.',
    news_wide_cta:       'See all results →',
    news_med_tag:        'Results',
    news_med_title:      'The young Ladybirds grow: podiums at the junior championships',
    news_med_excerpt:    'The young skaters proved their worth in the junior categories. Medals, smiles and the awareness of being part of something great. The future of Ladybirds is in good hands.',
    news_met_tag:        'Milano Easter Trophy',
    news_met_title:      'Milano Easter Trophy 2026: home ice, an audience from all over Europe',
    news_met_excerpt:    'The international competition organised by Ladybirds. Teams from all over Europe, emotions, music and the best of synchronized skating at the Palazzo del Ghiaccio.',
    news_met_cta:        'Visit the Trophy website →',
    news_archivio_kicker: 'Archive',
    news_mondiali_tag:   'Worlds',
    news_mondiali_title: 'Ladybirds reach the World Championships',
    news_mondiali_excerpt: 'Neuchâtel and Gothenburg. A goal that seemed distant, then closer and closer, then reality. Our girls on the ice of a world competition: the emotions of those who truly made it.',
    news_salone_tag:     'Club',
    news_salone_title:   'Ladybirds in Visit Milano\'s official campaign for Design Week',
    news_salone_excerpt: 'Chosen by Visit Milano and Salone del Mobile to represent the city during Milan Design Week. Our athletes in skates at the Central Station, with the Olympic logo. A story that tells who we are.',
    news_salone_cta:     'See the post →',

    /* ── ORDINE-DIVISE.HTML ── */
    order_nav_back:    '← Back to site',
    order_hero_h1:     'Uniform Order · Season 2026–2027',
    order_hero_p:      'Fill in the form, check the total and send the order by email',
    order_referente:   'Contact: <strong>Liana</strong>',
    order_tel:         'Tel. <strong>338 696 9823</strong> (after 6 pm)',
    order_total_lbl:   'Estimated total',
    order_dati_title:  'Athlete / Parent Details',
    order_atleta_lbl:  'Athlete name and surname *',
    order_genitore_lbl:'Parent / guardian name',
    order_email_lbl:   'Email *',
    order_tel_lbl:     'Phone',
    order_legend1:     '<span class="star">★</span> Required for Competitive Synchro',
    order_legend2:     '<span class="star">★★★</span> Required for Beginner Courses',
    order_note_title:  'Notes / Special requests',
    order_subtotal_title: 'Order summary',
    order_subtotal_tot:   'Estimated total <span class="note">* to be confirmed</span>',
    order_submit_btn:  '✉ Send order to Ladybirds',
    order_submit_note: 'The total is an estimate. You will be contacted within 2–3 working days for availability confirmation and payment.',
    order_confirm_h2:  'Order ready!',
    order_confirm_p1:  'Your email client will open with the order already filled in for <strong>divise@ladybirds.it</strong>.',
    order_confirm_warn:'⚠️ The total is an <strong>estimate</strong>. You will receive confirmation of availability and the final amount within <strong>2–3 working days</strong>.',
    order_confirm_btn: '📄 Download PDF and open email',
    order_confirm_cancel: '← Back to form',
  }
};

let currentLang = localStorage.getItem('lmsa_lang') || 'it';

function setLang(l) {
  currentLang = l;
  localStorage.setItem('lmsa_lang', l);
  document.querySelectorAll('[data-lang-key]').forEach(el => {
    const key = el.dataset.langKey;
    if (TRANSLATIONS[l][key] !== undefined) el.innerHTML = TRANSLATIONS[l][key];
  });
  // Update placeholder attributes separately
  document.querySelectorAll('[data-lang-placeholder]').forEach(el => {
    const key = el.dataset.langPlaceholder;
    if (TRANSLATIONS[l][key] !== undefined) el.placeholder = TRANSLATIONS[l][key];
  });
  // Update button
  const btn = document.getElementById('lang-btn');
  if (btn) btn.textContent = l === 'it' ? 'EN' : 'IT';
  // Update all mobile lang buttons
  document.querySelectorAll('.lang-btn-mobile').forEach(b => {
    b.textContent = l === 'it' ? 'IT / EN' : 'IT / EN';
  });
  // Update html lang attribute
  document.documentElement.lang = l === 'it' ? 'it' : 'en';
}

// Apply saved language on page load
document.addEventListener('DOMContentLoaded', function() {
  if (currentLang !== 'it') setLang(currentLang);
});
